# Generated by Django 3.0.4 on 2020-05-05 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterData', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('created_date', models.DateField(default=datetime.date(2020, 5, 5))),
                ('tags', models.ManyToManyField(to='MasterData.Tag')),
            ],
        ),
    ]
