# Generated by Django 3.0.4 on 2020-05-28 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='markdwon_content',
            new_name='markdown_content',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 5, 28)),
        ),
    ]
