# Generated by Django 3.0.4 on 2020-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('github_account', models.CharField(max_length=255)),
                ('linkdin_account', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
            ],
        ),
    ]
