# Generated by Django 3.0.4 on 2020-04-09 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 4, 9)),
        ),
    ]
