# Generated by Django 3.0.4 on 2020-04-11 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20200409_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 4, 11)),
        ),
    ]
