# Generated by Django 3.0.4 on 2020-04-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0002_responsibility'),
        ('Portfolio', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.ManyToManyField(to='MasterData.Responsibility'),
        ),
    ]
