# Generated by Django 3.0.4 on 2020-05-05 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20200420_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 5, 5)),
        ),
    ]
