# Generated by Django 3.0.4 on 2020-05-27 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_auto_20200505_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 5, 27)),
        ),
    ]
